name: DPy Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: DPy Action
        uses: DesigniteTools/DPyAction@v1.1.1
        with:
          PAT: ${{ secrets.PAT }}
      - name: DPy incremental code quality analysis and issue creation
        uses: DesigniteTools/dj-incremental-analysis@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          designite-output-old: designite-output-${{ github.event.before }}
          designite-output-new: designite-output-${{ github.sha }}
          repo-name: ${{ github.repository }}